apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-simple
  name: deploy-simple
spec:
  replicas: 3
  selector:
    matchLabels:
      app: po-simple
  template:
    metadata:
      labels:
        app: po-simple
    spec:
      containers:
        - image: boriswinter/simple:2.0
          name: deploy-simple

---

apiVersion: v1
kind: Service
metadata:
  name: simple
spec:
  selector:
    app: deploy-simple
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer